<testng-results>
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="3442" started-at="2011-05-22T00:28:54Z" finished-at="2011-05-22T00:28:58Z">
    <groups>
    </groups>
    <test name="testng.test.FunctionTest" duration-ms="3442" started-at="2011-05-22T00:28:54Z" finished-at="2011-05-22T00:28:58Z">
      <class name="testng.test.FunctionTest">
        <test-method status="FAIL" signature="f()" name="f" duration-ms="3418" started-at="2011-05-22T00:28:54Z" finished-at="2011-05-22T00:28:57Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.aidi.core.web.framework.ServiceAdapter.getServiceByName(ServiceAdapter.java:78)
	at cccf.ma.service.StateInfoServiceUtil.getAll(StateInfoServiceUtil.java:33)
	at testng.test.FunctionTest.f(FunctionTest.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:674)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:847)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1152)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:137)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:121)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1119)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:315)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:310)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:272)
	at org.testng.SuiteRunner.run(SuiteRunner.java:221)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:952)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:889)
	at org.testng.TestNG.run(TestNG.java:818)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:89)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:144)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
